### ISSUE TITLE
Remove specifying library version with SharedLibVersion

### ISSUE THREAD

**Issue by mdparker** [workhorsy/DerelictSQLite3#1]
Just an FYI. You don't need to override `configureMinimumVersion` in your loader unless you intend to support loading multiple versions of the shared library with the same loader. And if you're going to do that, you need to ensure that the different library versions you support actually are binary compatible.

The SDL maintainers, for example, are good about maintaining binary compatibility between patch versions. So when compiling against SDL 2.0.5, your program will still work with SDL 2.0.0. This is despite their doing things like adding new fields to event types in their patch updates. They can get away with it because they've padded `SDL_Event` with unused bytes. So DerelictSDL2 can safely load any version of the library and the `SDL_Event` type will always work with all of them. I don't know how they handle it with SQLite3, so if you intend to support `SharedLibVersion`, then you need to check into that. Otherwise, just don't bother overriding `configureMinimumVersion`. 

Most of the Derelict packages don't support `SharedLibVersion` and probably never will. For those, I update the minor version for each release that supports a new patch version of the C library and keep it in a separate branch.

**Comment by workhorsy** [comment]
Okay. I'll have to look more into how I'm going to handle different versions of sqlite3. I'll have look more into how configureMinimumVersion works and how API stable sqlite is.

Thanks

**Comment by workhorsy** [comment]
I'm going to remove SharedLibVersion for now. Sqlite3 seems API stable enough. Feel free to reopen this bug if anyone has an issue.
